In [8]:
import pandas as pd

In [26]:
df = pd.read_csv("weather.csv")

In [10]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [17]:
print("Rows are:", len(df))

Rows are: 96453

In [19]:
print("columns are:", len(df.columns))

columns are: 12

In [20]:
df[50:80]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
50,2006-04-11 02:00:00.000 +0200,Overcast,rain,8.633333,5.466667,0.87,22.0409,32.0,6.6976,0.0,1005.10,Foggy in the evening.
51,2006-04-11 03:00:00.000 +0200,Overcast,rain,11.250000,11.250000,0.83,11.3344,152.0,15.8263,0.0,1007.01,Foggy in the evening.
52,2006-04-11 04:00:00.000 +0200,Overcast,rain,11.183333,11.183333,0.89,11.2056,180.0,9.9015,0.0,1006.73,Foggy in the evening.
53,2006-04-11 05:00:00.000 +0200,Overcast,rain,10.694444,10.694444,0.95,10.4006,161.0,6.6976,0.0,1006.59,Foggy in the evening.
54,2006-04-11 06:00:00.000 +0200,Mostly Cloudy,rain,11.111111,11.111111,0.93,12.0106,140.0,5.9731,0.0,1006.34,Foggy in the evening.
55,2006-04-11 07:00:00.000 +0200,Mostly Cloudy,rain,11.111111,11.111111,0.93,9.2092,103.0,10.8031,0.0,1006.09,Foggy in the evening.
56,2006-04-11 08:00:00.000 +0200,Partly Cloudy,rain,12.166667,12.166667,0.82,9.9015,113.0,10.6743,0.0,1005.97,Foggy in the evening.
57,2006-04-11 09:00:00.000 +0200,Partly Cloudy,rain,12.755556,12.755556,0.79,13.8299,129.0,10.8192,0.0,1005.63,Foggy in the evening.
58,2006-04-11 10:00:00.000 +0200,Partly Cloudy,rain,13.838889,13.838889,0.84,9.0965,159.0,10.8192,0.0,1005.83,Foggy in the evening.
59,2006-04-11 11:00:00.000 +0200,Partly Cloudy,rain,16.183333,16.183333,0.73,0.6440,207.0,10.7548,0.0,1005.97,Foggy in the evening.
60,2006-04-11 12:00:00.000 +0200,Mostly Cloudy,rain,17.516667,17.516667,0.67,0.6762,153.0,10.8997,0.0,1005.64,Foggy in the evening.
61,2006-04-11 13:00:00.000 +0200,Mostly Cloudy,rain,17.383333,17.383333,0.67,3.8640,4.0,10.8514,0.0,1005.20,Foggy in the evening.
62,2006-04-11 14:00:00.000 +0200,Mostly Cloudy,rain,17.361111,17.361111,0.71,7.8246,341.0,11.0768,0.0,1005.10,Foggy in the evening.
63,2006-04-11 15:00:00.000 +0200,Mostly Cloudy,rain,17.205556,17.205556,0.74,15.5848,15.0,10.8514,0.0,1004.65,Foggy in the evening.
64,2006-04-11 16:00:00.000 +0200,Mostly Cloudy,rain,15.633333,15.633333,0.81,23.6992,348.0,10.8836,0.0,1004.04,Foggy in the evening.
65,2006-04-11 17:00:00.000 +0200,Overcast,rain,13.577778,13.577778,0.90,20.9622,321.0,7.6153,0.0,1004.08,Foggy in the evening.
66,2006-04-11 18:00:00.000 +0200,Foggy,rain,10.911111,10.911111,0.86,22.3951,311.0,2.6565,0.0,1004.61,Foggy in the evening.
67,2006-04-11 19:00:00.000 +0200,Foggy,rain,8.800000,5.294444,0.99,26.5006,339.0,2.6565,0.0,1004.99,Foggy in the evening.
68,2006-04-11 20:00:00.000 +0200,Overcast,rain,8.961111,5.777778,0.93,23.2162,340.0,3.8157,0.0,1004.85,Foggy in the evening.
69,2006-04-11 21:00:00.000 +0200,Overcast,rain,8.200000,4.605556,0.96,25.4219,330.0,4.4919,0.0,1004.96,Foggy in the evening.
70,2006-04-11 22:00:00.000 +0200,Overcast,rain,7.688889,3.722222,0.96,28.1267,339.0,4.4436,0.0,1005.14,Foggy in the evening.
71,2006-04-11 23:00:00.000 +0200,Overcast,rain,7.766667,4.650000,0.96,19.2878,339.0,5.6833,0.0,1005.05,Foggy in the evening.
72,2006-04-12 00:00:00.000 +0200,Foggy,rain,8.200000,5.072222,0.96,20.4470,341.0,3.1073,0.0,1004.80,Foggy overnight and breezy in the morning.
73,2006-04-12 01:00:00.000 +0200,Foggy,rain,8.177778,4.372222,0.93,27.8691,19.0,3.2039,0.0,1004.89,Foggy overnight and breezy in the morning.
74,2006-04-12 02:00:00.000 +0200,Mostly Cloudy,rain,7.311111,6.183333,0.82,6.7459,277.0,14.0553,0.0,1007.00,Foggy overnight and breezy in the morning.
75,2006-04-12 03:00:00.000 +0200,Overcast,rain,7.644444,5.038889,0.93,14.9086,9.0,6.1180,0.0,1004.30,Foggy overnight and breezy in the morning.
76,2006-04-12 04:00:00.000 +0200,Overcast,rain,6.622222,2.616667,0.93,25.0355,0.0,6.1180,0.0,1003.68,Foggy overnight and breezy in the morning.
77,2006-04-12 05:00:00.000 +0200,Overcast,rain,6.683333,3.222222,0.93,19.8352,350.0,6.1663,0.0,1003.86,Foggy overnight and breezy in the morning.
78,2006-04-12 06:00:00.000 +0200,Overcast,rain,6.088889,1.650000,0.93,28.0945,349.0,7.9695,0.0,1003.57,Foggy overnight and breezy in the morning.
79,2006-04-12 07:00:00.000 +0200,Overcast,rain,6.066667,1.633333,0.93,27.9818,348.0,6.3434,0.0,1003.96,Foggy overnight and breezy in the morning.

In [21]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [23]:
df['Temperature (C)'].min

<bound method Series.min of 0         9.472222
1         9.355556
2         9.377778
3         8.288889
4         8.755556
           ...
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Temperature (C), Length: 96453, dtype: float64>

In [25]:
df['Humidity'].tail

<bound method NDFrame.tail of 0        0.89
1        0.86
2        0.89
3        0.83
4        0.83
         ...
96448    0.43
96449    0.48
96450    0.56
96451    0.60
96452    0.61
Name: Humidity, Length: 96453, dtype: float64>